# Site settings
title: Tinker
email: fakeemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website for recording the projects I've done so far.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snickerton.github.io" # the base hostname & protocol for your site
github_username:  snickerton

# Build settings
markdown: kramdown
